# Generated by Django 3.2.8 on 2025-04-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherindicator',
            name='assigned_points',
        ),
    ]
