# Generated by Django 5.1.7 on 2025-04-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_teacherindicator_assigned_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherindicator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
